### ISSUE TITLE
Way to make success / error ?

### ISSUE THREAD

**Issue by NameX44** [icaksama/iProgressHUD#1]
Hi, 

Is there a way to do a success / error event when loading has finished ? Maybe I could help you to do it ?

Your library looks good !

Thanks,

**Comment by 1Caxz** [comment]
There is no way to do a success/error event for now. But, I have the plan to make them later and also download progress feature. It will great if you can make it happen faster. 
Please follow this step:
- [x] Create a personal fork of the main **iProgressHUD** repository in GitHub.
- [x] Make your changes in a named branch different from master, e.g. you create a branch my-awesome-feature.
- [x] Generate a pull request through the Web interface of GitHub.
